site_name: xterm
site_url: https://xterm.org
nav:
  - Home: 'index.md'
  - 'Story': 'story.md'
  - 'Install'
    - 'Package': 'package.md'
    - 'xterm.tar.gz': 'xterm.tar.gz.md'
  - 'Configure': 'configure.md'
  - 'Customize': 'customize.md'
    - 'Sample': 'sample.md'
    - 'Themes': 'themes.md'
    - 'Template': 'template.md'
    - 'Icon': 'icon.md'
    - 'Static window title': 'static-window-title.md'
    - 'Scrollbar': 'scrollbar.md'
    - 'Internal border': 'internal-border.md'
    - 'Window border': 'window-border.md'
  - 'Use': 'use.md'
    - 'Manpage': 'manpage.md'
      - 'xterm': 'manpage-xterm.md'
      - 'uxterm': 'manpage-uxterm.md'
      - 'koi8rxterm': 'manpage-koi8rxterm.md'
      - 'resize': 'manpage-resize.md'
    - 'Control sequences':
      - 'Getting started with control sequences': 'getting-started-with-ctlseqs.md'
      - 'Guide': 'ctlseqs-guide.md'
      - 'List': 'ctlseqs-list.md'
    - 'Copy-paste': 'copy-paste.md'
    - 'Tabs': 'tabs.md'
    - 'Full-screen': 'full-screen.md'
    - 'Scrolling': 'scrolling.md'
    - 'Prompt': 'prompt.md'
    - 'Dynamic window title': 'dynamic-window-title.md'
  - 'Release notes': 'release-notes.md'
  - 'Libraries': 'libraries.md'
    - 'Xcursor': 'xcursor.md'
    - 'Xft': 'xft.md'
  - 'Utilities':
    - 'Vttest':
      - 'About Vttest': 'vttest_about.md'
      - 'Vttest changes': 'vttest-changes.md'
    - 'Xtoolkit': 'xtoolkit.md'
    - 'Luit': 'luit.md'
