site_name: xterm
site_url: https://xterm.org
nav:
  - Home: 'index.md'
  - 'About':
    - 'Story': 'story.md'
    - 'FAQ': 'faq.md'
    - 'Terminal Icon': 'icon.md'
  - 'Install'
    - 'Package': 'package.md'
    - 'xterm.tar.gz': 'xterm.tar.gx.md'
  - 'Configure'
    - 'Procedure': 'configure.md'
    - 'Themes': 'xresources-themes.md'
    # = refer to the configuration procedure page
    # = theme n+1
       # * screenshot
       # * link to the sample Xresources file for HD-15-inch laptops that incorporates this theme
       # * link to the file containing only this theme (to be added into Xresources)
    - 'Template': 'xresources-template.md'
    # = refer to the configuration procedure page
    # = introduce the template Xresources file and explain that it's self-documenting
       # * link to the template Xresources file
  - 'Manpage':
    - 'xterm': 'manpage-xterm.md'
    - 'uxterm': 'manpage-uxterm.md'
    - 'koi8rxterm': 'manpage-koi8rxterm.md'
  - 'Control Sequences':
    -  'Guide': 'ctlseqs-guide.md'
    -  'List': 'ctlseqs-list.md'
  - 'Patch Log': 'log.md'
  - 'Utilities':
    - 'Vttest':
      - 'About Vttest': 'vttest.md'
      - 'Vttest Changes': 'changes.md'
    - 'Xtoolkit': 'xtoolkit.md'
    - 'Luit': 'luit.md'
