site_name: xterm
site_url: https://xterm.org
nav:
  - Home: 'index.md'
  - 'About':
    - 'Story': 'story.md' # rethink or keep the heading
       - 'TBD': # use https://invisible-island.net/xterm/xterm.faq.html#who_did_it
       - 'TBD': # https://invisible-island.net/xterm/xterm.icon.html
                  # From this page, link to the docs repo folder that is a copy of current-state
                  # https://github.com/ThomasDickey/xterm-snapshots/tree/master/icons.
  - 'Install'
    - 'Package': 'package.md'
    - 'xterm.tar.gz': 'xterm.tar.gx.md'
  - 'Configure': 'configure.md'
  - 'Customize': 'customize.md'
      # refer to the configuration procedure page
      # IMPORTANT! Make one single repo for .Xresources files with two repo folders, Samples and Themes, one file, Template, and one README.
    - 'Samples': 'samples.md' # content: link to the samples Github repo & clone that repo to the xterm-x11 org
    - 'Themes': 'themes.md'
      # refer to the configuration procedure page
      # theme n+1
         # * screenshot
         # * link to the sample Xresources file for HD-15-inch laptops that incorporates this theme
         # * link to the file containing only this theme (to be added into Xresources)
    - 'Template': 'template.md'
    # refer to the configuration procedure page
    # explain that this template file is self-documented
    - 'Icon': # TBD, if the new icon is adopted, then mention (a) different icon selection and (b) color customization.
    - 'Static window title': # TBD
       # explain the default user@host title and where it comes from
       # explictly do not recommend this route and cross-reference to the dynamically set title, the page under Use
    - 'Scrollbar': 'scrollbar.md'
    - 'Internal border': 'internal-border.md'
    - 'Window border': 'window-border.md'
  - 'Use' # select content from https://invisible-island.net/xterm/xterm.faq.html and https://invisible-island.net/xterm/#related-discussion
    # figure out a way to reference the manpage from each separate procedure page under Use, where applicable
    - 'Manpage': 'manpage.md' # content or even addition of the file under consideration
      - 'xterm': 'manpage-xterm.md'
      - 'uxterm': 'manpage-uxterm.md'
      - 'koi8rxterm': 'manpage-koi8rxterm.md'
      - 'resize': 'manpage-resize.md'
    - 'Control Sequences':
      - 'Getting started with control sequences': 'getting-started-with-ctlseqs.md'
      - 'Guide': 'ctlseqs-guide.md'
      - 'List': 'ctlseqs-list.md'
    - 'Copy-paste': 'copy-paste.md' # also describe text/lines selection process, including selection on the command line if possible
    - 'Tabs': 'tabs.md' # explain why tabs are not the best for a terminal emulator and explain how to achieve the tab-like behavior
    - 'Full-screen': 'full-screen.md'
    - 'Scrolling': 'scrolling.md'
    - 'Prompt': 'prompt.md'
    - 'Dynamic window title': 'dynamic-window-title.md' # cross-reference to the permanently set title, the page under Customize
       # Manually setting the title
       # Title ops in scripts
  - 'Release Notes': 'release-notes.md' # this is 'Patch Log': 'log.md' renamed
  - 'Libraries': 'libraries.md'
    - 'Xcursor': 'xcursor.md'
        # include the following content from https://github.com/xterm-x11/docs/blob/main/downstreaming-for-updates-from-invisible-island-net.sh:
          # https://invisible-island.net/xterm/xcursor/xcursor.html
    - 'Xft': 'xft.md'
        # include the following content from https://github.com/xterm-x11/docs/blob/main/downstreaming-for-updates-from-invisible-island-net.sh:
          # https://invisible-island.net/xterm/xft/xft.html
  - 'Utilities':
    - 'Vttest': # Investigate. Is this less important than Luit? If more important, then down after Luit.
      - 'About Vttest': 'vttest.md'
      - 'Vttest Changes': 'changes.md'
    - 'Xtoolkit': 'xtoolkit.md' # scope not clear yet
    - 'Luit': 'luit.md' 
      # see more pages (e.g., manpage) to include under this: https://github.com/xterm-x11/docs/blob/main/downstreaming-for-updates-from-invisible-island-net.sh
      # Investigate. Is this more important than Vttest? If more important, then move up before Vttest.
